config:
  framework: "foundry" 
  framework_version: "1.8.1" 
  node_version: "18" 
  package_manager: "yarn"

environment:
  MAX_SEGMENT_COUNT: "THE_MAX_SEGMENT_COUNT"
  MNEMONIC: "YOUR_MNEMONIC"
  ARBITRUM_RPC_URL: "YOUR_RPC_URL"
  ARBITRUM_SEPOLIA_RPC_URL: "YOUR_RPC_URL"
  AVALANCHE_RPC_URL: "YOUR_RPC_URL"
  BASE_RPC_URL: "YOUR_RPC_URL"
  BSC_RPC_URL: "YOUR_RPC_URL"
  GNOSIS_RPC_URL: "YOUR_RPC_URL"
  MAINNET_RPC_URL: "YOUR_RPC_URL"
  OPTIMISM_RPC_URL: "YOUR_RPC_URL"
  POLYGON_RPC_URL: "YOUR_RPC_URL"
  SCROLL_RPC_URL: "YOUR_RPC_URL"
  SEPOLIA_RPC_URL: "YOUR_RPC_URL"
  ARBISCAN_API_KEY: "YOUR_API_KEY"
  BASESCAN_API_KEY: "YOUR_API_KEY"
  BSCSCAN_API_KEY: "YOUR_API_KEY"
  ETHERSCAN_API_KEY: "YOUR_API_KEY"
  GNOSISSCAN_API_KEY: "YOUR_API_KEY"
  OPTIMISTIC_API_KEY: "YOUR_API_KEY"
  POLYGONSCAN_API_KEY: "YOUR_API_KEY"
  SCROLLSCAN_API_KEY: "YOUR_API_KEY"
  SNOWTRACE_API_KEY: "YOUR_API_KEY"
  API_KEY_INFURA: "YOUR_API_KEY_INFURA"
  EOA: "YOUR_EOA_ADDRESS"
  FOUNDRY_PROFILE: "lite"
  MNEMONIC: "YOUR_MNEMONIC"
  RPC_URL_MAINNET: "YOUR_RPC_URL_MAINNET"
  SPHINX_API_KEY: "YOUR_API_KEY"
  SPHINX_ORG_ID: "YOUR_ORG_ID"
  SPHINX_PROJECT_NAME: "YOUR_PROJECT_NAME"

tasks:
  install-dependencies:
    - yarn install
    - forge install --no-commit sablier-labs/v2-core
    - forge install --no-commit OpenZeppelin/openzeppelin-contracts@v5.0.0 PaulRBerg/prb-math